# Generated by Django 4.0.4 on 2022-05-16 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='uuid',
            new_name='course_uuid',
        ),
    ]
