# Generated by Django 4.0.4 on 2022-05-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_address_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='users',
        ),
    ]
